swagger: '2.0'
info:
  version: 0.0.1
  title: Opal-Cache
  license:
    name: MIT
    url: 'https://github.com/opal-project/opal-interface/blob/master/LICENSE'
  description: OPAL Cache
paths:
  /status:
    get:
      description: Status report. Part of the standard API for all the opal components
      responses:
        '200':
          description: 'Status report is active, replies the current status'
          schema:
            type: object
            description: Status report
            properties:
              status:
                type: string
                description: MUST be one of EAE_SERVICE_STATUS_XXX
                example: eae_service_idle
  /specs:
    get:
      description: Detailed status report. Part of the standard API for eae components
      responses:
        '200':
          description: desc
          schema:
            $ref: '#/definitions/statusModel'




  /query:
    post:
      description: Submit a query
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      parameters:
        - name: request body
          in: body
          schema:
            type: object
            required:
              - opalUsername
              - opalUserToken
              - startDate
              - endDate
              - algorithm
              - parameters
              - aggregationLevel
              - aggregationValue
              - sample
            properties:
              opalUsername:
                type: string
              opalUserToken:
                type: string
              startDate:
                type: string
              endDate:
                type: string
              algorithm:
                type: string
              parameters:
                type: object
              aggregationLevel:
                type: string
              aggregationValue:
                type: string
              sample:
                type: string
            example:
              opalUsername: admin
              opalUserToken: admin
              startDate: "01/01/13T00:00:00Z"
              endDate: "01/01/13T00:00:00Z"
              algorithm: density
              parameters: {a: "something", b: "something else"}
              aggregationLevel: tower
              aggregationValue: tower_id1
              sample: 0.2


      responses:
        '200':
          description: Sends back the query result
          schema:
            type: object
        '404':
          description: The query has not been found
        '401':
          description: The request is not well formed
          schema:
            type: object
            description: eAE ErrorStack tracking the error origin
        '500':
          description: Internal mongo or server error.
          schema:
            type: object
            description: eAE ErrorStack tracking the error origin


  /result:
    post:
      description: Submit the result for a query
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      parameters:
        - name: request body
          in: body
          schema:
            type: object
            required:
              - opalUsername
              - opalUserToken
              - queryID
              - queryResult
            properties:
              opalUsername:
                type: string
              opalUserToken:
                type: string
              queryID:
                type: string
              queryResult:
                type: object
            example:
              opalUsername: admin
              opalUserToken: admin
              queryID: "abcdef"
              queryResult: {count: 56256}
      responses:
        '200':
          description: Result received successfully
        '401':
          description: The request is not well formed
          schema:
            type: object
            description: eAE ErrorStack tracking the error origin
        '500':
          description: Internal mongo or server error.
          schema:
            type: object
            description: eAE ErrorStack tracking the error origin
