version: '3'
services:
    mongodb:
        image: mongo:latest@sha256:07212fb304ea36b8c5a9e5694527f16deeb0b99f87fc60162dc15ab260bf8a2a
        environment:
            - MONGO_DATA_DIR=/data/mongodb
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_DBNAME=opal
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        ports:
            - 27017:27017

    cache:
        build:
            context: .
        depends_on:
            - mongodb
        links:
            - mongodb
        ports:
            - 80:80
