version: '3'
services:
    mongodb:
        image: mongo:latest@sha256:bac22ea7710d774103dcad3ec8ac13cba1eb378f488e3ce8a6b3a1adf2ba9dcc
        environment:
            - MONGO_DATA_DIR=/data/mongodb
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_DBNAME=opal
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        ports:
            - 27017:27017

    cache:
        build:
            context: .
        depends_on:
            - mongodb
        links:
            - mongodb
        ports:
            - 80:80
