version: '3'
services:
    mongodb:
        image: mongo:latest@sha256:9342a9279a9841fc5f8192e49dcaaf9404e6bb3a90e8cf134eb96074830dd448
        environment:
            - MONGO_DATA_DIR=/data/mongodb
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_DBNAME=opal
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        ports:
            - 27017:27017

    cache:
        build:
            context: .
        depends_on:
            - mongodb
        links:
            - mongodb
        ports:
            - 80:80
