version: '3'
services:
    mongodb:
        image: mongo:latest@sha256:81a1c8842a09589fc8d5f285266f3340bf4abdf66700ba22988f14cc9b2b3118
        environment:
            - MONGO_DATA_DIR=/data/mongodb
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_DBNAME=opal
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        ports:
            - 27017:27017

    cache:
        build:
            context: .
        depends_on:
            - mongodb
        links:
            - mongodb
        ports:
            - 80:80
