version: '3'
services:
    mongodb:
        image: mongo:latest@sha256:64be89e169fc33f3fa140c2c548186be4acd972bd7174344505fc5630dcf707c
        environment:
            - MONGO_DATA_DIR=/data/mongodb
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_DBNAME=opal
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        ports:
            - 27017:27017

    cache:
        build:
            context: .
        depends_on:
            - mongodb
        links:
            - mongodb
        ports:
            - 80:80
